// 模拟从后端获取的路由数据
export default <PageRouteItem[]>[
  {
    id: "/home",
    parent: null,
    order_num: 1,
    path: "/home",
    element: "/Home/index",
    meta: {
      label: "首页",
      icon: "TdesignHome",
      isRouter: true,
    },
  },
  {
    id: "/blank-page",
    parent: null,
    order_num: 0,
    path: "/blank",
    element: "/BlankPage/index",
    meta: {
      label: "空白页",
      icon: "TdesignHome",
      isRouter: true,
    },
  },
  // {
  //   id: "/textparse",
  //   parent: null,
  //   order_num: 1,
  //   path: "/textparse",
  //   element: "/TextParser/index",
  //   meta: {
  //     label: "文本转换",
  //     icon: "TdesignTable1",
  //     isRouter: true,
  //   },
  // },
  {
    id: "sub1",
    parent: null,
    order_num: 2,
    path: null,
    element: null,
    meta: {
      label: "表格",
      icon: "TdesignGridView",
      isRouter: false,
    },
  },
  {
    id: "/basictable",
    parent: "sub1",
    order_num: 1,
    path: "/basictable",
    element: "/Tables/BasicTable",
    meta: {
      label: "基础表格",
      icon: "TdesignTable1",
      isRouter: true,
    },
  },
  {
    id: "/formtable",
    parent: "sub1",
    order_num: 2,
    path: "/formtable",
    element: "/Tables/FormTable",
    meta: {
      label: "完整表格",
      icon: "TdesignTable",
      isRouter: true,
    },
  },
  {
    id: "/usertable",
    parent: "sub1",
    order_num: 2,
    path: "/usertable",
    element: "/Tables/UserTable",
    meta: {
      label: "用户管理",
      icon: "TdesignUserAvatar",
      isRouter: true,
    },
  },
  {
    id: "transfer",
    parent: null,
    order_num: 3,
    path: null,
    element: null,
    meta: {
      label: "转换",
      icon: "TdesignGridView",
      isRouter: false,
    },
  },
  {
    id: "/json-diff",
    parent: null,
    order_num: 4,
    path: "/json-diff",
    element: "/JsonDiffViewPage/index",
    meta: {
      label: "json-diff",
      icon: "TdesignGridView",
      isRouter: true,
    },
  },
  {
    id: "/text",
    parent: "transfer",
    order_num: 1,
    path: "/text-parse",
    element: "/TextParser/index",
    meta: {
      label: "文本转换",
      icon: "TdesignTable1",
      isRouter: true,
    },
  },
  {
    id: "sub2",
    parent: null,
    order_num: 3,
    path: null,
    element: null,
    meta: {
      label: "异常页",
      icon: "TdesignChatBubbleError",
      isRouter: false,
    },
  },
  {
    id: "systemManagers",
    parent: null,
    order_num: 5,
    path: null,
    element: null,
    meta: { label: "系统管理", icon: "TdesignTable1", isRouter: false },
  },
  {
    id: "systemTenant",
    parent: "systemManagers",
    order_num: 2,
    path: null,
    element: null,
    type: "group",
    meta: { label: "租户管理", icon: "TdesignTable1", isRouter: false },
  },
  {
    id: "list",
    parent: "systemTenant",
    order_num: 1,
    path: "/system/tenant/list",
    element: "/System/Tenant/List/index",
    meta: { label: "租户列表", isRouter: true },
  },
  {
    id: "/403",
    parent: "sub2",
    order_num: 1,
    path: "/403",
    element: "/Error/403",
    meta: {
      label: "403",
      icon: "TdesignErrorCircle",
      isRouter: true,
    },
  },
  {
    id: "/404",
    parent: "sub2",
    order_num: 2,
    path: "/404",
    element: "/Error/404",
    meta: {
      label: "404",
      icon: "TdesignErrorTriangle",
      isRouter: true,
    },
  },
];
